apiVersion: v1
kind: Service
metadata:
  name: zwavejs
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: ws
      port: 3000
      targetPort: ws
  selector:
    name: zwavejs