apiVersion: v1
kind: Service
metadata:
  name: mqtt
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mosquitto.k3s.ingenstans.se.
    metallb.universe.tf/address-pool: default
spec:
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      port: 8883
      name: mqtt-tls
    - protocol: TCP
      port: 443
      name: websocket-tls
  type: LoadBalancer